//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsEnhancementSuite.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsEnhancementSuite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;Window xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///        xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///        Title=&quot;CommandBar&quot; Width=&quot;800&quot; Height=&quot;600&quot;
        ///        AllowsTransparency=&quot;True&quot; WindowStyle=&quot;None&quot;
        ///        ResizeMode=&quot;NoResize&quot; WindowStartupLocation=&quot;Manual&quot;
        ///        WindowState=&quot;Normal&quot; ShowInTaskbar=&quot;False&quot;&gt;
        ///    &lt;Window.Background&gt;
        ///        &lt;SolidColorBrush Opacity=&quot;0.6&quot; Color=&quot;Black&quot;/&gt;
        ///    &lt;/Window.Background&gt;
        ///    &lt;Grid x:Name=&quot;GridMain&quot;/&gt;
        ///&lt;/Window&gt; ähnelt.
        /// </summary>
        internal static string ApplicationBar {
            get {
                return ResourceManager.GetString("ApplicationBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;Window xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///        xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///        Title=&quot;CommandBar&quot; Width=&quot;800&quot; Height=&quot;600&quot;
        ///        AllowsTransparency=&quot;True&quot; WindowStyle=&quot;None&quot;
        ///        ResizeMode=&quot;NoResize&quot; WindowStartupLocation=&quot;Manual&quot;
        ///        WindowState=&quot;Normal&quot; ShowInTaskbar=&quot;False&quot;
        ///        FocusManager.FocusedElement=&quot;{Binding ElementName=commandTextBox}&quot;&gt;
        ///    &lt;Window.Background&gt;
        ///        &lt;SolidColorBrush Opacity=&quot;0.6&quot; Color=&quot;Blac [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string CommandBar {
            get {
                return ResourceManager.GetString("CommandBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon executable {
            get {
                object obj = ResourceManager.GetObject("executable", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon other {
            get {
                object obj = ResourceManager.GetObject("other", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon WES {
            get {
                object obj = ResourceManager.GetObject("WES", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
